version: '3'
services:
  rabbit:
    image: "rabbitmq"
    restart: always
  producer:
    build:
      context: .
      dockerfile: DockerfileProducer
    restart: always
    links:
     - rabbit
    ports:
     - "5000:5000"
  consumer:
    build:
      context: .
      dockerfile: DockerfileConsumer
    restart: always
    links:
     - rabbit
